### ISSUE TITLE
The contact role does not appear updated in the consortium organization list when logged in as a consortium lead

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#541]
#### Expected Behaviour

Once the contact role has been added in the member settings it appears updated in in the consortium organization list view

#### Current Behaviour

The role is does not appear updated and the message: Service Contact "Please provide this information". appears. **This is only reproducible when logged in with a consortium account**

#### Steps to Reproduce

https://doi.test.datacite.org/providers/dc/organizations

<img width="1386" alt="Screen Shot 2021-04-21 at 16 22 54" src="https://user-images.githubusercontent.com/44582654/115572037-d4f1c600-a2bf-11eb-9b1c-6105f8407de1.png">

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ogt1)

**Comment by svogt0511** [comment]
Just checked this out.  I logged in as a datacite consortium admin.  It does not appear to be a problem anymore.  Perhaps it was fixed in work done in the interim.  Closing this.

**Comment by MaryHirsch** [comment]
I can still reproduce this becuase I can still reproduce this:

<img width="1160" alt="Screen Shot 2021-04-29 at 16 43 12" src="https://user-images.githubusercontent.com/44582654/116569863-14e12a80-a90a-11eb-8249-5eebb1eab7e2.png">


<img width="1391" alt="Screen Shot 2021-04-29 at 16 42 43" src="https://user-images.githubusercontent.com/44582654/116569850-127ed080-a90a-11eb-8e87-1d0278c0ffec.png">

**Comment by MaryHirsch** [comment]
In addition, when logged in with a Consortium Organization account the contact roles appear updated. But they do not appear when logged in with the Consortium lead account.

**Comment by errortryagain** [comment]
We are facing the same issue as consortium leads in the list of Consortium Organizations:

![grafik](https://user-images.githubusercontent.com/87866100/126995706-88d75047-85f2-4db9-8fe4-4d471b9e7967.png)

Unfortunately, not even after a hard refresh of the page can we see the contacts, even though they have been provided by our members.

**Comment by svogt0511** [comment]
I found out what is happening with the scenario described by Mary and other users. 

A good example of this is in staging at the [DataCite Consortium organization list tab](https://doi.stage.datacite.org/providers/dc/organizations).  When logged in as the consortium_admin (dc), no service contacts are listed for any of the organizations, even if the organization has a contact designated for this purpose.  When logged in as a staff_admin, the information shows up appropriately.

The problem is not in Fabrica.  Fabrica is executing the same code and making the same call to Lupo, regardless of which role the user has.  Lupo is returning different information depending on the user role.  Staff_admin users get full information (including contact information).  Consortium_admin users get all information (minus contact information).

This can be seen by comparing the output of the following API request when making the following API call with different credentials.

```
https://api.stage.datacite.org/providers?consortium-id=dc&focus-area=&has-required-contacts&include-deleted&non-profit-status&organization-type&page[number]=1&page[size]=25&page[include]=contacts&region&size=25&sort&year
```
@richardhallett I need advice on where to take this.  We can talk.  In the meantime I will check out https://github.com/datacite/bracco/issues/549#issuecomment-948604423 to see if it is the same thing.
